version: '2'
services:
  db:
    read_only: false
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: arqui2
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  app:
    read_only: false
    build: .
    image: gcr.io/t-arqui/arqui2:v1
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/arqui2"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: arqui2
      DB_PASSWORD: password
      DB_HOST: db
